# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FnwF2ijHjfxPQ3XHgrhj3LpkW9YpNMA0
"""

import numpy as np
import pandas as pd
from bs4 import BeautifulSoup 
import re
import requests

# import os
# os.environ['PATH'] += 'path'
# we can use this later if we care enough

from googleapiclient.discovery import build
yt = build('youtube', 'v3', developerKey='AIzaSyB7lyhbFr1Q_uDc6KAGQW359ObiPEtuUFE')

def getInfo(username):
  print('getting email from desc:')
  #make the URL
  a = "https://youtube.com/@" + username + "/about"
  # r = requests.get(a)
  # useThis = r.text.replace('\n',' ').replace(',','')
  # print(useThis)
  # searchCriteria = re.compile(("[-A-Za-z0-9!#$%&'*+/=?^_`{|}~]+(?:\.[-A-Za-z0-9!#$%&'*+/=?^_`{|}~]+)*@(?:[A-Za-z0-9](?:[-A-Za-z0-9]*[A-Za-z0-9])?\.)+[A-Za-z0-9](?:[-A-Za-z0-9]*[A-Za-z0-9])?")) #this is from regex generator
  # email = re.search(searchCriteria, useThis).group(0)
  # print(email)
  print(email_from_description(a))

def email_from_description(url): #this is the best i could try
  r = requests.get(url)
  HTMLData = BeautifulSoup(r.text)
  c = HTMLData.find("meta",{'property':"og:description"})
  c = str(c).replace('\n',' ').replace(',','')
  print(c)
  s2 = re.compile((r"[-A-Za-z0-9!#$%&'*+/=?^_`{|}~]+(?:\.[-A-Za-z0-9!#$%&'*+/=?^_`{|}~]+)*@(?:[A-Za-z0-9](?:[-A-Za-z0-9]*[A-Za-z0-9])?\.)+[A-Za-z0-9](?:[-A-Za-z0-9]*[A-Za-z0-9])?"))
  s = re.compile('[^"]*', re.IGNORECASE)
  emailLn = re.findall(s,c)
  emailLn=emailLn[2]
  email = re.findall(s2,emailLn)
  return (email[0])

getInfo('AhmadAlKaashekh')